## **Requirements**
1. When you work on this assignment, you should make a copy of this notebook in Google Colab. This can be done using the option `File > Save a copy in Drive` in Google Colab.

2. You should fill in your answer for each task inside the code block right under the task.

3. You should only insert your code into the designated code blocks, as mentioned above. Other than that, you shouldn't change anything else in the notebook, unless otherwise instructed.

4.  For each code block, you are free to use multiple lines of code.

5.   Even if you can only partially solve a task, you should include your code in the code block, which allows us to consider partial credit.

6.   However, your code should not raise errors. Any code raising errors will not get partial credit.

7.   We will test your code in Google Colab. Make sure your code runs in Google Colab.

10. To submit your assignment, download your Colab into a .ipynb file. This can be done using the option `Download > Download .ipynb` in Google Colab.

11. Submit the downloaded .ipynb file into the Programming Assignment 3 entry in Canvas.

## **Task1: Pandas:DataFrame**(60)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# DATA URL SOURCES ###############################
eng_url     = 'https://andybek.com/pandas-eng'
state_url   = 'https://andybek.com/pandas-state'
party_url   = 'https://andybek.com/pandas-party'
liberal_url = 'https://andybek.com/pandas-liberal'
ivies_url   = 'https://andybek.com/pandas-ivies'
##################################################

In [ ]:
#Create 5 dataframes(eng,state,party,liberal,ivies) from the 5 csv files uploaded above.
eng = pd.read_csv(eng_url)
state = pd.read_csv(state_url)
party = pd.read_csv(party_url)
liberal = pd.read_csv(liberal_url)
ivies = pd.read_csv(ivies_url)

eng.info()
state.info()
party.info()
liberal.info()
ivies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               19 non-null     object
 1   School Type               19 non-null     object
 2   Starting Median Salary    19 non-null     object
 3   Mid-Career Median Salary  19 non-null     object
dtypes: object(4)
memory usage: 736.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               175 non-null    object
 1   School Type               175 non-null    object
 2   Starting Median Salary    175 non-null    object
 3   Mid-Career Median Salary  175 non-null    object
dtypes: object(4)
memory usage: 5.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               20 non-null     object
 1   School Type               20 non-null     object
 2   Starting Median Salary    20 non-null     object
 3   Mid-Career Median Salary  20 non-null     object
dtypes: object(4)
memory usage: 768.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               47 non-null     object
 1   School Type               47 non-null     object
 2   Starting Median Salary    47 non-null     object
 3   Mid-Career Median Salary  47 non-null     object
dtypes: object(4)
memory usage: 1.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               8 non-null      object
 1   School Type               8 non-null      object
 2   Starting Median Salary    8 non-null      object
 3   Mid-Career Median Salary  8 non-null      object
dtypes: object(4)
memory usage: 384.0+ bytes

In [ ]:
#Use a function to retreive information on the first 10 rows of your dataframe.
display(eng.head(10))
display(state.head(10))
display(party.head(10))
display(liberal.head(10))
display(ivies.head(10))

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
5,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00"
6,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00"
7,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00"
8,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00"
9,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00"

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,"University of California, Berkeley",State,"$59,900.00","$112,000.00"
1,University of Virginia (UVA),State,"$52,700.00","$103,000.00"
2,Cal Poly San Luis Obispo,State,"$57,200.00","$101,000.00"
3,University of California at Los Angeles (UCLA),State,"$52,600.00","$101,000.00"
4,"University of California, San Diego (UCSD)",State,"$51,100.00","$101,000.00"
5,"University of California, Davis",State,"$52,300.00","$99,600.00"
6,University of Colorado - Boulder (UCB),State,"$47,100.00","$97,600.00"
7,"University of California, Irvine (UCI)",State,"$48,300.00","$96,700.00"
8,University of Illinois at Urbana-Champaign (UIUC),State,"$52,900.00","$96,100.00"
9,Texas A&M University,State,"$49,700.00","$96,100.00"

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,University of Illinois at Urbana-Champaign (UIUC),Party,"$52,900.00","$96,100.00"
1,"University of Maryland, College Park",Party,"$52,000.00","$95,000.00"
2,"University of California, Santa Barbara (UCSB)",Party,"$50,500.00","$95,000.00"
3,University of Texas (UT) - Austin,Party,"$49,700.00","$93,900.00"
4,State University of New York (SUNY) at Albany,Party,"$44,500.00","$92,200.00"
5,University of Florida (UF),Party,"$47,100.00","$87,900.00"
6,Louisiana State University (LSU),Party,"$46,900.00","$87,800.00"
7,University of Georgia (UGA),Party,"$44,100.00","$86,000.00"
8,Pennsylvania State University (PSU),Party,"$49,900.00","$85,700.00"
9,Arizona State University (ASU),Party,"$47,400.00","$84,100.00"

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00"
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00"
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00"
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00"
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00"
5,College of the Holy Cross,Liberal Arts,"$50,200.00","$106,000.00"
6,Occidental College,Liberal Arts,"$51,900.00","$105,000.00"
7,Washington and Lee University,Liberal Arts,"$53,600.00","$104,000.00"
8,Swarthmore College,Liberal Arts,"$49,700.00","$104,000.00"
9,Davidson College,Liberal Arts,"$46,100.00","$104,000.00"

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Dartmouth College,Ivy League,"$58,000.00","$134,000.00"
1,Princeton University,Ivy League,"$66,500.00","$131,000.00"
2,Yale University,Ivy League,"$59,100.00","$126,000.00"
3,Harvard University,Ivy League,"$63,400.00","$124,000.00"
4,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
5,Cornell University,Ivy League,"$60,300.00","$110,000.00"
6,Brown University,Ivy League,"$56,200.00","$109,000.00"
7,Columbia University,Ivy League,"$59,400.00","$107,000.00"

In [ ]:
#Concatenate eng and ivies using the Pandas concatination function and give the shape of your dataframes
eng_ivies = pd.concat([eng, ivies])
eng_ivies.shape
eng_ivies.head()

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"

In [ ]:
#Concatenate the 5 dataframes and drop the duplicated values of 'School Name' in your output dataframe called schools
df = pd.concat([eng, state, party, liberal, ivies])
df.info()
schools = df.drop_duplicates(subset='School Name')
schools.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 269 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               269 non-null    object
 1   School Type               269 non-null    object
 2   Starting Median Salary    269 non-null    object
 3   Mid-Career Median Salary  269 non-null    object
dtypes: object(4)
memory usage: 10.5+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 249 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               249 non-null    object
 1   School Type               249 non-null    object
 2   Starting Median Salary    249 non-null    object
 3   Mid-Career Median Salary  249 non-null    object
dtypes: object(4)
memory usage: 9.7+ KB

In [ ]:
#Check if the index in schools is diplicated or not
check_duplicates = schools.index.duplicated().any()
print("Is there any duplicated index in schools DataFrame: ", check_duplicates)

Is there any duplicated index in schools DataFrame:  True

In [ ]:
# Does schools.loc[0:2] works? and why?
schools.loc[0:2]

#This works if the DataFrame index is default integer index. Since it has duplicated index in it, the loc (expplicit) does not work here.

KeyError: ignored

In [ ]:
#Explain how to fix the duplicated index problem.
schools_fixed = schools.reset_index(drop=True)
#we can reset the index to fix the duplicated index problem. This method replaces the current index and creates a new one.

In [ ]:
# Create eng2 and ivies2 from eng and ivies where the index is Set to 'School Name'.

eng2 = eng.set_index('School Name')
eng2.head()
ivies2 = ivies.set_index('School Name')
ivies2.head()

,School Type,Starting Median Salary,Mid-Career Median Salary
School Name,,,
Dartmouth College,Ivy League,"$58,000.00","$134,000.00"
Princeton University,Ivy League,"$66,500.00","$131,000.00"
Yale University,Ivy League,"$59,100.00","$126,000.00"
Harvard University,Ivy League,"$63,400.00","$124,000.00"
University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"

In [ ]:
#Concatenate eng and ivies by using the multi-index in order to remove the duplicated index issue.
eng_ivies_c = pd.concat([eng, ivies], keys=['Eng', 'Ivies'])
eng_ivies_c
#we can also use use multi-indexing to remove duplicated indexing by adding a layer of index

                                                School Name  School Type  \
Eng   0         Massachusetts Institute of Technology (MIT)  Engineering
      1            California Institute of Technology (CIT)  Engineering
      2                                 Harvey Mudd College  Engineering
      3        Polytechnic University of New York, Brooklyn  Engineering
      4                                        Cooper Union  Engineering
      5               Worcester Polytechnic Institute (WPI)  Engineering
      6                    Carnegie Mellon University (CMU)  Engineering
      7              Rensselaer Polytechnic Institute (RPI)  Engineering
      8                     Georgia Institute of Technology  Engineering
      9                            Colorado School of Mines  Engineering
      10                    Stevens Institute of Technology  Engineering
      11             Illinois Institute of Technology (IIT)  Engineering
      12                  Wentworth Institute of Technology  Engineering
      13  Virginia Polytechnic Institute and State Unive...  Engineering
      14          South Dakota School of Mines & Technology  Engineering
      15  New Mexico Institute of Mining and Technology ...  Engineering
      16            Rochester Institute of Technology (RIT)  Engineering
      17        Embry-Riddle Aeronautical University (ERAU)  Engineering
      18                 Tennessee Technological University  Engineering
Ivies 0                                   Dartmouth College   Ivy League
      1                                Princeton University   Ivy League
      2                                     Yale University   Ivy League
      3                                  Harvard University   Ivy League
      4                          University of Pennsylvania   Ivy League
      5                                  Cornell University   Ivy League
      6                                    Brown University   Ivy League
      7                                 Columbia University   Ivy League

         Starting Median Salary Mid-Career Median Salary
Eng   0             $72,200.00              $126,000.00
      1             $75,500.00              $123,000.00
      2             $71,800.00              $122,000.00
      3             $62,400.00              $114,000.00
      4             $62,200.00              $114,000.00
      5             $61,000.00              $114,000.00
      6             $61,800.00              $111,000.00
      7             $61,100.00              $110,000.00
      8             $58,300.00              $106,000.00
      9             $58,100.00              $106,000.00
      10            $60,600.00              $105,000.00
      11            $56,000.00               $97,800.00
      12            $53,000.00               $96,700.00
      13            $53,500.00               $95,400.00
      14            $55,800.00               $93,400.00
      15            $51,000.00               $93,400.00
      16            $48,900.00               $84,600.00
      17            $52,700.00               $80,700.00
      18            $46,200.00               $80,000.00
Ivies 0             $58,000.00              $134,000.00
      1             $66,500.00              $131,000.00
      2             $59,100.00              $126,000.00
      3             $63,400.00              $124,000.00
      4             $60,900.00              $120,000.00
      5             $60,300.00              $110,000.00
      6             $56,200.00              $109,000.00
      7             $59,400.00              $107,000.00

In [ ]:
#Use the append function to concatenate 'liberal' and 'party' dataframes
liberal_party_c = liberal.append(party, ignore_index=True)
liberal_party_c
#The DataFrame.append method is deprecated and will be removed from pandas in a future version. Its better to use pandas.concat instead.

<ipython-input-28-802218232a92>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  liberal_party_c = liberal.append(party, ignore_index=True)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00"
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00"
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00"
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00"
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00"
...,...,...,...,...
62,University of New Hampshire (UNH),Party,"$41,800.00","$78,300.00"
63,West Virginia University (WVU),Party,"$43,100.00","$78,100.00"
64,University of Tennessee,Party,"$43,800.00","$74,600.00"
65,Ohio University,Party,"$42,200.00","$73,400.00"
66,Florida State University (FSU),Party,"$42,100.00","$73,000.00"

In [ ]:
regions_url = 'https://andybek.com/pandas-regions'

In [ ]:
# Create the dataframe 'regions'
regions = pd.read_csv(regions_url)
regions

                                      School Name        Region
0     Massachusetts Institute of Technology (MIT)  Northeastern
1        California Institute of Technology (CIT)    California
2                             Harvey Mudd College    California
3    Polytechnic University of New York, Brooklyn  Northeastern
4                                    Cooper Union  Northeastern
..                                            ...           ...
264                  Austin Peay State University      Southern
265                    Pittsburg State University    Midwestern
266                      Southern Utah University       Western
267           Montana State University - Billings       Western
268                  Black Hills State University    Midwestern

[269 rows x 2 columns]

In [ ]:
# Merge the 2 dataframes schools and regions
sch_reg_merged = pd.merge(schools, regions)
sch_reg_merged

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",Northeastern
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",California
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",California
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",Northeastern
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",Northeastern
...,...,...,...,...,...
264,Harvard University,Ivy League,"$63,400.00","$124,000.00",Northeastern
265,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00",Northeastern
266,Cornell University,Ivy League,"$60,300.00","$110,000.00",Northeastern
267,Brown University,Ivy League,"$56,200.00","$109,000.00",Northeastern
268,Columbia University,Ivy League,"$59,400.00","$107,000.00",Northeastern

In [ ]:
# Merge schools and regions on the column name 'School Name'
school_Name_merged = pd.merge(schools, regions, on='School Name')
school_Name_merged
#By defult, in the above merge, the pandas finds any default column to perform the merge and later in this cell,
#we are explicitly specifying to consider the merge using the column "School Name".

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",Northeastern
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",California
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",California
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",Northeastern
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",Northeastern
...,...,...,...,...,...
264,Harvard University,Ivy League,"$63,400.00","$124,000.00",Northeastern
265,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00",Northeastern
266,Cornell University,Ivy League,"$60,300.00","$110,000.00",Northeastern
267,Brown University,Ivy League,"$56,200.00","$109,000.00",Northeastern
268,Columbia University,Ivy League,"$59,400.00","$107,000.00",Northeastern

In [ ]:
income_url = 'https://andybek.com/pandas-mid'

In [ ]:
#Create Dataframe (mid_career) from the file income
mid_career = pd.read_csv(income_url)
mid_career

,school_name,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Massachusetts Institute of Technology (MIT),"$76,800.00","$99,200.00","$168,000.00","$220,000.00"
1,California Institute of Technology (CIT),NaN,"$104,000.00","$161,000.00",NaN
2,Harvey Mudd College,NaN,"$96,000.00","$180,000.00",NaN
3,"Polytechnic University of New York, Brooklyn","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
4,Cooper Union,NaN,"$80,200.00","$142,000.00",NaN
...,...,...,...,...,...
264,Austin Peay State University,"$32,200.00","$40,500.00","$73,900.00","$96,200.00"
265,Pittsburg State University,"$25,600.00","$46,000.00","$84,600.00","$117,000.00"
266,Southern Utah University,"$30,700.00","$39,700.00","$78,400.00","$116,000.00"
267,Montana State University - Billings,"$22,600.00","$31,800.00","$78,500.00","$98,900.00"
268,Black Hills State University,"$27,000.00","$32,200.00","$60,900.00","$87,600.00"

In [ ]:
# Merge mid_career and schools on the arguments left_on and right_on and drop the duplicated column.
merged_ms = pd.merge(mid_career, schools, left_on='school_name', right_on='School Name')
print(merged_ms)
merged_midc_sch = merged_ms.drop(columns='school_name')
print(merged_midc_sch)

                                      school_name  \
0     Massachusetts Institute of Technology (MIT)
1        California Institute of Technology (CIT)
2                             Harvey Mudd College
3    Polytechnic University of New York, Brooklyn
4                                    Cooper Union
..                                            ...
264                  Austin Peay State University
265                    Pittsburg State University
266                      Southern Utah University
267           Montana State University - Billings
268                  Black Hills State University

    Mid-Career 10th Percentile Salary Mid-Career 25th Percentile Salary  \
0                         $76,800.00                        $99,200.00
1                                 NaN                      $104,000.00
2                                 NaN                       $96,000.00
3                         $66,800.00                        $94,300.00
4                                 NaN                       $80,200.00
..                                ...                               ...
264                       $32,200.00                        $40,500.00
265                       $25,600.00                        $46,000.00
266                       $30,700.00                        $39,700.00
267                       $22,600.00                        $31,800.00
268                       $27,000.00                        $32,200.00

    Mid-Career 75th Percentile Salary Mid-Career 90th Percentile Salary  \
0                        $168,000.00                       $220,000.00
1                        $161,000.00                                NaN
2                        $180,000.00                                NaN
3                        $143,000.00                       $190,000.00
4                        $142,000.00                                NaN
..                                ...                               ...
264                       $73,900.00                        $96,200.00
265                       $84,600.00                       $117,000.00
266                       $78,400.00                       $116,000.00
267                       $78,500.00                        $98,900.00
268                       $60,900.00                        $87,600.00

                                      School Name  School Type  \
0     Massachusetts Institute of Technology (MIT)  Engineering
1        California Institute of Technology (CIT)  Engineering
2                             Harvey Mudd College  Engineering
3    Polytechnic University of New York, Brooklyn  Engineering
4                                    Cooper Union  Engineering
..                                            ...          ...
264                  Austin Peay State University        State
265                    Pittsburg State University        State
266                      Southern Utah University        State
267           Montana State University - Billings        State
268                  Black Hills State University        State

    Starting Median Salary Mid-Career Median Salary
0              $72,200.00              $126,000.00
1              $75,500.00              $123,000.00
2              $71,800.00              $122,000.00
3              $62,400.00              $114,000.00
4              $62,200.00              $114,000.00
..                     ...                      ...
264            $37,700.00               $59,200.00
265            $40,400.00               $58,200.00
266            $41,900.00               $56,500.00
267            $37,900.00               $50,600.00
268            $35,300.00               $43,900.00

[269 rows x 9 columns]
    Mid-Career 10th Percentile Salary Mid-Career 25th Percentile Salary  \
0                         $76,800.00                        $99,200.00
1                                 NaN                      $104,000.00
2                                 NaN                       $96,000.00
3                         $66,800.00                        $94,300.00
4                                 NaN                       $80,200.00
..                                ...                               ...
264                       $32,200.00                        $40,500.00
265                       $25,600.00                        $46,000.00
266                       $30,700.00                        $39,700.00
267                       $22,600.00                        $31,800.00
268                       $27,000.00                        $32,200.00

    Mid-Career 75th Percentile Salary Mid-Career 90th Percentile Salary  \
0                        $168,000.00                       $220,000.00
1                        $161,000.00                                NaN
2                        $180,000.00                                NaN
3                        $143,000.00                       $190,000.00
4                        $142,000.00                                NaN
..                                ...                               ...
264                       $73,900.00                        $96,200.00
265                       $84,600.00                       $117,000.00
266                       $78,400.00                       $116,000.00
267                       $78,500.00                        $98,900.00
268                       $60,900.00                        $87,600.00

                                      School Name  School Type  \
0     Massachusetts Institute of Technology (MIT)  Engineering
1        California Institute of Technology (CIT)  Engineering
2                             Harvey Mudd College  Engineering
3    Polytechnic University of New York, Brooklyn  Engineering
4                                    Cooper Union  Engineering
..                                            ...          ...
264                  Austin Peay State University        State
265                    Pittsburg State University        State
266                      Southern Utah University        State
267           Montana State University - Billings        State
268                  Black Hills State University        State

    Starting Median Salary Mid-Career Median Salary
0              $72,200.00              $126,000.00
1              $75,500.00              $123,000.00
2              $71,800.00              $122,000.00
3              $62,400.00              $114,000.00
4              $62,200.00              $114,000.00
..                     ...                      ...
264            $37,700.00               $59,200.00
265            $40,400.00               $58,200.00
266            $41,900.00               $56,500.00
267            $37,900.00               $50,600.00
268            $35,300.00               $43,900.00

[269 rows x 8 columns]

Q1: Concatenate the *liberal* and *state* schools into a new dataframe. How many unique school names are there?

In [ ]:
#Q1:Code
concat_df = pd.concat([liberal, state], ignore_index=True)
#finding the number of unique school names
unique_sql_name = concat_df['School Name'].nunique()
print("Number of unique school names:", unique_sql_name)
concat_df

Number of unique school names: 222

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00"
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00"
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00"
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00"
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00"
...,...,...,...,...
217,Austin Peay State University,State,"$37,700.00","$59,200.00"
218,Pittsburg State University,State,"$40,400.00","$58,200.00"
219,Southern Utah University,State,"$41,900.00","$56,500.00"
220,Montana State University - Billings,State,"$37,900.00","$50,600.00"
221,Black Hills State University,State,"$35,300.00","$43,900.00"

Q2: What is the average median starting salary in the dataframe created above?

In [ ]:
#Q2:Code

concat_df['Starting Median Salary'] = concat_df['Starting Median Salary'].replace('[\$,]', '', regex=True).astype(float)
average_median_starting_salary = concat_df['Starting Median Salary'].mean()
print("Average Starting median salary", average_median_starting_salary)

Average Starting median salary 44469.36936936937

Q3: Create a short dataframe that shows the top 3 *liberal* arts and *state* schools that produce the highest (mid-career) earning graduates.

Show the *School Name* and *Mid-Career Median Salary* columns from each dataset, side by side, i.e. <ins>horizontally</ins>.

Nest the column labels within 'Liberal Arts' and 'State' labels.

In [ ]:
#Q3:Code
liberal_sorted = liberal.sort_values(by='Mid-Career Median Salary', ascending=False)
top3_liberal = liberal_sorted.head(3)

state_sorted = state.sort_values(by='Mid-Career Median Salary', ascending=False)
top3_state = state_sorted.head(3)

nested_lib_st = pd.concat({'Liberal Arts': top3_liberal[['School Name', 'Mid-Career Median Salary']],
                           'State': top3_state[['School Name', 'Mid-Career Median Salary']]}, axis=1)
nested_lib_st

                                     Liberal Arts                           \
                                      School Name Mid-Career Median Salary
13  Wesleyan University (Middletown, Connecticut)              $97,900.00
14                                  Bates College              $96,500.00
15                                  Union College              $95,800.00
5                                             NaN                      NaN
6                                             NaN                      NaN
7                                             NaN                      NaN

                                     State
                               School Name Mid-Career Median Salary
13                                     NaN                      NaN
14                                     NaN                      NaN
15                                     NaN                      NaN
5          University of California, Davis              $99,600.00
6   University of Colorado - Boulder (UCB)              $97,600.00
7   University of California, Irvine (UCI)              $96,700.00

Q4: Merge *liberal* arts schools with *regions* and assign the resulting dataframe to *dfm*. What region has the highest number of liberal arts schools?

In [ ]:
#Q4:Code
dfm = pd.merge(liberal, regions)
liberal_reg = dfm.groupby('Region')['School Name'].count()
top_liberal_reg = liberal_reg.idxmax()
print("Region that has the highest number of liberal arts schools:", top_liberal_reg)

Region that has the highest number of liberal arts schools: Northeastern

Q5: Set *school_name* as the index of the *mid_career* dataframe. Do the operation inplace.

In [ ]:
#Q5:Code
mid_career.set_index('school_name', inplace=True)
mid_career

,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
school_name,,,,
Massachusetts Institute of Technology (MIT),"$76,800.00","$99,200.00","$168,000.00","$220,000.00"
California Institute of Technology (CIT),NaN,"$104,000.00","$161,000.00",NaN
Harvey Mudd College,NaN,"$96,000.00","$180,000.00",NaN
"Polytechnic University of New York, Brooklyn","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
Cooper Union,NaN,"$80,200.00","$142,000.00",NaN
...,...,...,...,...
Austin Peay State University,"$32,200.00","$40,500.00","$73,900.00","$96,200.00"
Pittsburg State University,"$25,600.00","$46,000.00","$84,600.00","$117,000.00"
Southern Utah University,"$30,700.00","$39,700.00","$78,400.00","$116,000.00"
Montana State University - Billings,"$22,600.00","$31,800.00","$78,500.00","$98,900.00"
Black Hills State University,"$27,000.00","$32,200.00","$60,900.00","$87,600.00"

Q6: Merge the *dfm* and *mid_career* dataframes. Is the join operation one-to-one?

In [ ]:
#Q6:Code
merged_dfm_midc = pd.merge(dfm, mid_career, left_on='School Name', right_on='school_name')
merged_dfm_midc.head()
#checking if the join operation is one to one
is_one_to_one = merged_dfm_midc['School Name'].is_unique

print("\nIs the join operation one-to-one?", is_one_to_one)
merged_dfm_midc.head()

Is the join operation one-to-one? False

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00",Northeastern,"$62,800.00","$80,600.00","$156,000.00","$251,000.00"
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00",Northeastern,"$60,000.00","$76,700.00","$167,000.00","$265,000.00"
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00",Northeastern,NaN,"$84,900.00","$162,000.00",NaN
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00",Northeastern,"$70,600.00","$79,300.00","$144,000.00","$204,000.00"
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00",Northeastern,NaN,"$74,600.00","$146,000.00",NaN

Create dataframe games

In [ ]:
#Dataframe creation
games_url = 'https://andybek.com/pandas-games'
games = pd.read_csv(games_url)
games

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
1,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
2,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
3,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
4,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
...,...,...,...,...,...,...,...,...,...,...
3138,Bound By Flame,X360,2014.0,Role-Playing,NaN,0.00,0.01,0.00,0.00,0.01
3139,Mighty No. 9,XOne,2016.0,Platform,Deep Silver,0.01,0.00,0.00,0.00,0.01
3140,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.00,0.00,0.01
3141,Farming 2017 - The Simulation,PS4,2016.0,Simulation,UIG Entertainment,0.00,0.01,0.00,0.00,0.01
3142,Rugby Challenge 3,XOne,2016.0,Sports,Alternative Software,0.00,0.01,0.00,0.00,0.01

Q7: What are the total sales across all regions?

In [ ]:
#Q7-Code
total_sales = games[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']].sum()
total_sales

NA_Sales        1173.30
EU_Sales         793.64
JP_Sales         107.06
Other_Sales      282.75
Global_Sales    2356.96
dtype: float64

 Q8: Find the total sales by region for X360 and PS3.

In [ ]:
#8-Code
total_sales_region = games[games['Platform'].isin(['X360', 'PS3'])].groupby('Platform')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']].sum()
total_sales_region

          NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Platform
PS3         392.26    343.71     79.99       141.93        957.84
X360        601.05    280.58     12.43        85.54        979.96

Q9: How much does each platform sell across regions, on average?

In [ ]:
avg_sales = games.groupby('Platform')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']].mean()
avg_sales

          NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Platform
PS3       0.295154  0.258623  0.060188     0.106795      0.720722
PS4       0.288095  0.368155  0.042560     0.129048      0.827679
X360      0.475138  0.221802  0.009826     0.067621      0.774672
XOne      0.390563  0.214319  0.001596     0.055962      0.662254

Q10: Create a smaller dataframe from *games*, selecting only the Publisher, Genre, Platform, and NA_Sales columns. Assign this dataframe to the variable *publishers*.

In [ ]:
#Q10-Code

publishers = games[['Publisher', 'Genre', 'Platform', 'NA_Sales']]
publishers

                   Publisher         Genre Platform  NA_Sales
0     Microsoft Game Studios          Misc     X360     14.97
1       Take-Two Interactive        Action      PS3      7.01
2       Take-Two Interactive        Action     X360      9.63
3                 Activision       Shooter     X360      9.03
4                 Activision       Shooter     X360      9.67
...                      ...           ...      ...       ...
3138                     NaN  Role-Playing     X360      0.00
3139             Deep Silver      Platform     XOne      0.01
3140                  Capcom       Shooter     XOne      0.01
3141       UIG Entertainment    Simulation      PS4      0.00
3142    Alternative Software        Sports     XOne      0.00

[3143 rows x 4 columns]

Q11: From the *publishers* dataframe, find the top 10 game publishers in North America by total sales.

In [ ]:
#Q11-Code
publisher_top10 = publishers.groupby('Publisher')['NA_Sales'].sum().sort_values(ascending=False).head(10)
publisher_top10

Publisher
Electronic Arts                           213.38
Activision                                193.16
Take-Two Interactive                      120.99
Microsoft Game Studios                    116.77
Ubisoft                                    98.65
Sony Computer Entertainment                76.35
Warner Bros. Interactive Entertainment     45.24
THQ                                        36.44
Bethesda Softworks                         33.88
Capcom                                     24.74
Name: NA_Sales, dtype: float64

Q12: What is the gaming platform that has attracted the most sales in North America?

In [ ]:
#Q12:Code
top_platforms = games.groupby("Platform")['NA_Sales'].sum()

max_sales_platform = top_platforms.idxmax()
print("The gaming platform that has attracted the most sales in North America is", max_sales_platform)

The gaming platform that has attracted the most sales in North America is X360

In [ ]:
#Create Dataframe sat
sat_url = 'https://andybek.com/pandas-sat'

sat = pd.read_csv(sat_url)
sat

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.00%,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.00%,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.00%,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.90%,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.90%,Reading,422
...,...,...,...,...,...,...
1120,Young Women's Leadership School in Astoria,Queens,572,100.00%,Reading,464
1121,Young Women's Leadership School in Astoria,Queens,572,100.00%,Writing,477
1122,Young Women's Leadership School in Queens,Queens,557,90.40%,Math,415
1123,Young Women's Leadership School in Queens,Queens,557,90.40%,Reading,420
1124,Young Women's Leadership School in Queens,Queens,557,90.40%,Writing,433

Q13: Starting with our main dataframe (*sat*), create a pivot table that summarizes the <ins>total</ins> student enrollment (Student Enrollment) across all 5 boroughs (*Borough*).

Which boroughs have the highest and lowest high school student bodies?

In [ ]:
#Q13
sat['Percent Tested'] = pd.to_numeric(sat['Percent Tested'].str.rstrip('%'))
enrollment = sat.pivot_table(values='Student Enrollment', index='Borough', aggfunc='sum')
print(enrollment)
borough_highest = enrollment.idxmax()
borough_lowest = enrollment.idxmin()
print("Borough having the highest School Student Body:", borough_highest)
print("Borough having the lowest School Student Body:", borough_lowest)

               Student Enrollment
Borough
Bronx                      159267
Brooklyn                   242814
Manhattan                  170370
Queens                     232437
Staten Island               55380
Borough having the highest School Student Body: Student Enrollment    Brooklyn
dtype: object
Borough having the lowest School Student Body: Student Enrollment    Staten Island
dtype: object

Q14: Modify the pivot table from the step above to also reflect the average student body size (*Student Enrollment*) across boroughs, in the same pivot table.

In [ ]:
#Q14

enrollment = sat.pivot_table(values='Student Enrollment', index='Borough', aggfunc=['sum', 'mean'])
enrollment.columns = ['Total Students Enrollment', 'Average Students Enrollment']
borough_highest_total = enrollment['Total Students Enrollment'].idxmax()
borough_lowest_total = enrollment['Total Students Enrollment'].idxmin()
print("Borough having the highest Total Student Body:", borough_highest_total)
print("Borough having the lowest Total Student Body:", borough_lowest_total)
enrollment

Borough having the highest Total Student Body: Brooklyn
Borough having the lowest Total Student Body: Staten Island

               Total Students Enrollment  Average Students Enrollment
Borough
Bronx                             159267                   541.724490
Brooklyn                          242814                   742.550459
Manhattan                         170370                   638.089888
Queens                            232437                  1122.884058
Staten Island                      55380                  1846.000000

Q15: Create a pivot table of high schools from the Queens borough (*Borough*), containing the SAT section scores (*SAT Section*, *Score*) as columns and the school name (*School Name*) as index. Sort the table in descending order by math section scores.

In [ ]:
#Q15
Queens_borough = sat[(sat['Borough'] == 'Queens') & (sat['School Name'].notna())]
Queens_borough_p = Queens_borough.pivot_table(values='Score', index='School Name', columns='SAT Section')
Queens_high_schools_p = Queens_borough_p.sort_values(by='Math', ascending=False)
Queens_high_schools_p

SAT Section                                         Math  Reading  Writing
School Name
Queens High School for the Sciences at York Col...   701      621      625
Townsend Harris High School                          680      640      661
Baccalaureate School for Global Education            633      620      628
Bard High School Early College Queens                631      598      610
Scholars' Academy                                    588      560      568
...                                                  ...      ...      ...
Middle College High School at LaGuardia Communi...   377      389      377
Queens High School for Information, Research, a...   372      362      352
August Martin High School                            366      372      364
Rockaway Park High School for Environmental Sus...   357      381      376
Pan American International High School               340      320      318

[69 rows x 3 columns]